### ISSUE TITLE
Compare the final playlist that is combined to see if there are any extra songs that were added.

### ISSUE THREAD

**Issue by Llucy14** [CS180-spring/cs180-22-slang#12]
Test case for combine playlist user story. #6

**Comment by athai026** [comment]
Objective: 
- To verify the final playlist of two or more combined playlists does not have any extra or missing song.

Preconditions: 
- Two or more playlists that are ready to be combined.
- The user must input URLs of the playlists they want to combine.

Expected Outcomes: 
- No extra songs are added to the final playlist.
- Duplicate songs should be removed.
- The number of songs in the final playlist should be less than or equal to the sum of all songs in the inputted playlists.

Test Results: 
- A single playlists that has all unique songs from the inputted playlists.
